<?php
/**
 * PersonModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MLVerify\Client
 * @author   MLVerify Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ML Verify API (version 1.0)
 *
 * Use this page for testing and prototyping ML Verify API features
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * MLVerify Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MLVerify\Client;

/**
 * PersonModelTest Class Doc Comment
 *
 * @category    Class
 * @description PersonModel
 * @package     MLVerify\Client
 * @author      MLVerify Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PersonModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PersonModel"
     */
    public function testPersonModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "middle_name"
     */
    public function testPropertyMiddleName()
    {
    }

    /**
     * Test attribute "surname"
     */
    public function testPropertySurname()
    {
    }

    /**
     * Test attribute "dob_day"
     */
    public function testPropertyDobDay()
    {
    }

    /**
     * Test attribute "dob_month"
     */
    public function testPropertyDobMonth()
    {
    }

    /**
     * Test attribute "dob_year"
     */
    public function testPropertyDobYear()
    {
    }

    /**
     * Test attribute "nationality"
     */
    public function testPropertyNationality()
    {
    }

    /**
     * Test attribute "relationship"
     */
    public function testPropertyRelationship()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "is_associated_person"
     */
    public function testPropertyIsAssociatedPerson()
    {
    }
}
