<?php
/**
 * ClientsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MLVerify\Client
 * @author   MLVerify Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ML Verify API (version 1.0)
 *
 * Use this page for testing and prototyping ML Verify API features
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * MLVerify Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MLVerify\Client;

use \MLVerify\Client\Configuration;
use \MLVerify\Client\ApiException;
use \MLVerify\Client\ObjectSerializer;

/**
 * ClientsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MLVerify\Client
 * @author   MLVerify Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClientsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for clientsDelete
     *
     * Deletes client.
     *
     */
    public function testClientsDelete()
    {
    }

    /**
     * Test case for clientsGet
     *
     * Gets client by id.
     *
     */
    public function testClientsGet()
    {
    }

    /**
     * Test case for clientsGetAll
     *
     * Gets clients by search criteria.
     *
     */
    public function testClientsGetAll()
    {
    }

    /**
     * Test case for clientsPost
     *
     * Creates client.
     *
     */
    public function testClientsPost()
    {
    }

    /**
     * Test case for clientsPut
     *
     * Updates client.
     *
     */
    public function testClientsPut()
    {
    }

    /**
     * Test case for clientsSendKycCheck
     *
     * Sends client access request.
     *
     */
    public function testClientsSendKycCheck()
    {
    }
}
