<?php
/**
 * KycChecksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MLVerify\Client
 * @author   MLVerify Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ML Verify API (version 1.0)
 *
 * Use this page for testing and prototyping ML Verify API features
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * MLVerify Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MLVerify\Client;

use \MLVerify\Client\Configuration;
use \MLVerify\Client\ApiException;
use \MLVerify\Client\ObjectSerializer;

/**
 * KycChecksApiTest Class Doc Comment
 *
 * @category Class
 * @package  MLVerify\Client
 * @author   MLVerify Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KycChecksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for kycChecksDelete
     *
     * Deletes KYC check.
     *
     */
    public function testKycChecksDelete()
    {
    }

    /**
     * Test case for kycChecksGet
     *
     * Gets KYC check by id.
     *
     */
    public function testKycChecksGet()
    {
    }

    /**
     * Test case for kycChecksGetAll
     *
     * Gets KYC checks by search criteria.
     *
     */
    public function testKycChecksGetAll()
    {
    }

    /**
     * Test case for kycChecksPost
     *
     * Creates KYC check.
     *
     */
    public function testKycChecksPost()
    {
    }

    /**
     * Test case for kycChecksPut
     *
     * Updates KYC check.
     *
     */
    public function testKycChecksPut()
    {
    }

    /**
     * Test case for kycChecksRespond
     *
     * Updates KYC check response.
     *
     */
    public function testKycChecksRespond()
    {
    }
}
